### ISSUE TITLE
USBEndpoint object has no attribute device_class

### ISSUE THREAD

**Issue by bhass1** [usb-tools/Facedancer#33]
While testing out nu-map (https://github.com/sprout42/nu-map/tree/umap2_python3_updates) against facedancer's current master branch (2281b57b579f), I encounter the following error:

[ERROR ] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numap-2.0.2-py3.6.egg/numap/apps/scan.py", line 50, in run
    device.run()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 166, in run
    self.scheduler.run()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/core.py", line 506, in run
    task()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 84, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 756, in service_irqs
    self._handle_transfer_events()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 470, in _handle_transfer_events
    self._handle_transfer_complete_on_endpoint(i, self.HOST_TO_DEVICE)
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 556, in _handle_transfer_complete_on_endpoint
    self.connected_device.handle_request(self.pending_control_request)
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 236, in handle_request
    handler_entity = recipient.device_class
AttributeError: 'USBEndpoint' object has no attribute 'device_class'

I still need to investigate a bit further to see why USBEndpoint causes this.

**Comment by bhass1** [comment]
I get a similar issue when trying to use `usb-emulate -C mass_storage` :

[ERROR ] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numap-2.0.2-py3.6.egg/numap/apps/emulate.py", line 42, in run
    self.dev.run()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 166, in run
    self.scheduler.run()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/core.py", line 506, in run
    task()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 84, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 755, in service_irqs
    self._handle_setup_events()
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 362, in _handle_setup_events
    self._handle_setup_event_on_endpoint(i)
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/backends/GreatDancerApp.py", line 396, in _handle_setup_event_on_endpoint
    self.connected_device.handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/Facedancer-2019.3.2-py3.6.egg/facedancer/USBDevice.py", line 236, in handle_request
    handler_entity = recipient.device_class
AttributeError: 'USBMassStorageInterface' object has no attribute 'device_class'

**Comment by bhass1** [comment]
By the way, this appears to be DUT / host behavior related. Mass-storage emulator worked when the DUT was my Ubuntu 18.04 laptop, but not the other DUT I am focused on. I will try to post more logs tonight.

**Comment by bhass1** [comment]
numap-scan log (not DUT dependent, both choke on the same packet from host):
![image](https://user-images.githubusercontent.com/5995272/74999606-12dc2b80-542a-11ea-8e7b-d168501311ac.png)
