### ISSUE TITLE
Trying to facedancer-usbproxy.py a Roland Boutique D-05 sound module

### ISSUE THREAD

**Issue by jaffa225man** [usb-tools/Facedancer#47]
It's probably silly, but I just purchased the GreatFET One to try illuminating what the ALSA driver is missing, that windows isn't, to get the Roland Boutique D-05's USB digital audio working under GNU/Linux.

Since facedancer-usbproxy.py didn't work at all with the 2018 firmware the GreatFET One arrived with, I updated its firmware to the current git:

```
gf info
Found a GreatFET One!
  Board ID: 0
  Firmware version: git-v2020.1.2-18-g12efb0f
  Part ID: a0000a30724f6e
  Serial number: 000057cc67e631177857
```

With the current firmware I definitely have gotten a lot farther, as it waits for me to plug into the target (windows computer) before crashing.  A USB keyboard, rather than the D-05, works perfectly, by the way.  

This is what the Roland Boutique D-05 looks like to lsusb -v:
```
Bus 001 Device 005: ID 0582:01ff Roland Corp. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol       255 
  bMaxPacketSize0        64
  idVendor           0x0582 Roland Corp.
  idProduct          0x01ff 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x010e
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      2 
      iInterface              0 
      ** UNRECOGNIZED:  06 24 f1 01 00 00
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      2 
      iInterface              0 
      ** UNRECOGNIZED:  07 24 01 01 00 01 00
      ** UNRECOGNIZED:  0b 24 02 01 02 04 18 01 00 77 01
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0d  EP 13 OUT
        bmAttributes            5
          Transfer Type            Isochronous
          Synch Type               Asynchronous
          Usage Type               Data
        wMaxPacketSize     0x0070  1x 112 bytes
        bInterval               1
        INTERFACE CLASS:  06 24 f1 04 12 00
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       2
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      2 
      iInterface              0 
      ** UNRECOGNIZED:  07 24 01 01 00 01 00
      ** UNRECOGNIZED:  0b 24 02 01 02 04 18 01 00 77 01
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0d  EP 13 OUT
        bmAttributes            5
          Transfer Type            Isochronous
          Synch Type               Asynchronous
          Usage Type               Data
        wMaxPacketSize     0x0070  1x 112 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      1 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      1 
      iInterface              0 
      ** UNRECOGNIZED:  07 24 01 07 00 01 00
      ** UNRECOGNIZED:  0b 24 02 01 02 04 18 01 00 77 01
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x8e  EP 14 IN
        bmAttributes           37
          Transfer Type            Isochronous
          Synch Type               Asynchronous
          Usage Type               Implicit feedback Data
        wMaxPacketSize     0x0070  1x 112 bytes
        bInterval               1
        INTERFACE CLASS:  06 24 f1 04 12 00
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       2
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      2 
      bInterfaceProtocol      1 
      iInterface              0 
      ** UNRECOGNIZED:  07 24 01 07 00 01 00
      ** UNRECOGNIZED:  0b 24 02 01 02 04 18 01 00 77 01
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x8e  EP 14 IN
        bmAttributes           37
          Transfer Type            Isochronous
          Synch Type               Asynchronous
          Usage Type               Implicit feedback Data
        wMaxPacketSize     0x0070  1x 112 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      3 
      bInterfaceProtocol      0 
      iInterface              0 
      ** UNRECOGNIZED:  06 24 f1 02 01 01
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      3 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               4
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               4
```

And here's how facedancer reacts to it:
```
#./facedancer-usbproxy.py -v 0582 -p 01ff
Using GreatDancer backend.
GreatDancer initialized
[23:41:01] <, standard request to device (GET_DESCRIPTOR: value=DEVICE descriptor (index=0x00), index=0, length=64)
[23:41:01] <: b'\x12\x01\x00\x02\xff\x00\xff@\x82\x05\xff\x01\x00\x01\x01\x02\x03\x01'
-- Patched device descriptor. --
[23:41:01] <, standard request to device (GET_DESCRIPTOR: value=DEVICE descriptor (index=0x00), index=0, length=18)
[23:41:01] <: b'\x12\x01\x00\x02\xff\x00\xff@\x82\x05\xff\x01\x00\x01\x01\x02\x03\x01'
-- Patched device descriptor. --
[23:41:01] <, standard request to device (GET_DESCRIPTOR: value=CONFIGURATION descriptor (index=0x00), index=0, length=255)
[23:41:01] <: b'\t\x02\x0e\x01\x04\x01\x00\x80\xfa\t\x04\x00\x00\x00\xff\xff\x00\x00\t\x04\x01\x00\x00\xff\x02\x02\x00\x06$\xf1\x01\x00\x00\t\x04\x01\x01\x01\xff\x02\x02\x00\x07$\x01\x01\x00\x01\x00\x0b$\x02\x01\x02\x04\x18\x01\x00w\x01\x07\x05\r\x05p\x00\x01\x07%\x01\x00\x00\x00\x00\x06$\xf1\x04\x12\x00\t\x04\x01\x02\x01\xff\x02\x02\x00\x07$\x01\x01\x00\x01\x00\x0b$\x02\x01\x02\x04\x18\x01\x00w\x01\x07\x05\r\x05p\x00\x01\x07%\x01\x00\x00\x00\x00\t\x04\x02\x00\x00\xff\x02\x01\x00\t\x04\x02\x01\x01\xff\x02\x01\x00\x07$\x01\x07\x00\x01\x00\x0b$\x02\x01\x02\x04\x18\x01\x00w\x01\x07\x05\x8e%p\x00\x01\x07%\x01\x00\x00\x00\x00\x06$\xf1\x04\x12\x00\t\x04\x02\x02\x01\xff\x02\x01\x00\x07$\x01\x07\x00\x01\x00\x0b$\x02\x01\x02\x04\x18\x01\x00w\x01\x07\x05\x8e%p\x00\x01\x07%\x01\x00\x00\x00\x00\t\x04\x03\x00\x02\xff\x03\x00\x00\x06$\xf1\x02\x01\x01\x07\x05\x03\x02\x00\x02\x01\x07\x05\x84\x02\x00\x02\x00\t\x04\x03\x01\x02\xff\x03\x00'
Traceback (most recent call last):
  File "./facedancer-usbproxy.py", line 50, in <module>
    main()
  File "./facedancer-usbproxy.py", line 44, in main
    d.run()
  File "/usr/src/Facedancer/facedancer/USBDevice.py", line 165, in run
    self.scheduler.run()
  File "/usr/src/Facedancer/facedancer/core.py", line 509, in run
    task()
  File "/usr/src/Facedancer/facedancer/USBDevice.py", line 83, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/usr/src/Facedancer/facedancer/backends/greatdancer.py", line 765, in service_irqs
    self._handle_setup_events()
  File "/usr/src/Facedancer/facedancer/backends/greatdancer.py", line 368, in _handle_setup_events
    self._handle_setup_event_on_endpoint(i)
  File "/usr/src/Facedancer/facedancer/backends/greatdancer.py", line 402, in _handle_setup_event_on_endpoint
    self.connected_device.handle_request(request)
  File "/usr/src/Facedancer/facedancer/USBProxy.py", line 239, in handle_request
    self._proxy_in_request(req)
  File "/usr/src/Facedancer/facedancer/USBProxy.py", line 277, in _proxy_in_request
    req, data, stalled = f.filter_control_in(req, data, stalled)
  File "/usr/src/Facedancer/facedancer/filters/standard.py", line 51, in filter_control_in
    configuration = USBDescribable.from_binary_descriptor(data)
  File "/usr/src/Facedancer/facedancer/USB.py", line 83, in from_binary_descriptor
    return subclass.from_binary_descriptor(data)
  File "/usr/src/Facedancer/facedancer/USBConfiguration.py", line 58, in from_binary_descriptor
    interfaces = cls._parse_subordinate_descriptors(data[length:total_length])
  File "/usr/src/Facedancer/facedancer/USBConfiguration.py", line 78, in _parse_subordinate_descriptors
    descriptor = USBDescribable.from_binary_descriptor(data[:length])
  File "/usr/src/Facedancer/facedancer/USB.py", line 83, in from_binary_descriptor
    return subclass.from_binary_descriptor(data)
  File "/usr/src/Facedancer/facedancer/USBInterface.py", line 82, in from_binary_descriptor
    = struct.unpack_from("xxBBBBBBB", data)
struct.error: unpack_from requires a buffer of at least 9 bytes for unpacking 9 bytes at offset 0 (actual buffer size is 8)
```

I've tried editing facedancer here and there, but so far haven't found anything that keeps the device descriptor data and works.  Aside from looking at python in the past, this is my first real attempt editing it, though.  This problem looked different enough from what others have posted, so I hope there's an easy, straightforward solution.

Thanks for any ideas you can offer,

  Luke

**Comment by jaffa225man** [comment]
Although the issue shown here probably still exists, I don't need it solved (for this purpose/device anyway) because many Roland devices are now working for USB-audio on recent kernels with auto-detection and configuration.  That's due to the amazing dedication of, ALSA kernel developer, Takashi Iwai!: https://patchwork.kernel.org/project/alsa-devel/patch/20210422120413.457-2-tiwai@suse.de/

**Comment by straithe** [comment]
Thank you for the update. @jaffa225man and I'm sorry we didn't get to this issue while it was still fresh.
